name: Publish to GitHub Packages

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore ./net-dns.sln

      - name: Build
        run: dotnet build ./net-dns.sln --configuration Release --no-restore

      - name: Compute package version from release tag
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION=${TAG#v}
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack libraries
        run: |
          dotnet pack ./src/Dns/Dns.csproj --configuration Release --no-build --output ./artifacts -p:Version=$PACKAGE_VERSION
          dotnet pack ./src/Mdns/Mdns.csproj --configuration Release --no-build --output ./artifacts -p:Version=$PACKAGE_VERSION

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget add source \
            --username "${{ github.repository_owner }}" \
            --password "$GITHUB_TOKEN" \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push "./artifacts/*.nupkg" --source github --skip-duplicate
